#pragma once
#include "CoreMinimal.h"
#include "ESHMapsEnum.generated.h"

UENUM(BlueprintType)
enum class ESHMapsEnum : uint8 {
    None,
    FogTest,
    RoadToCity = 9,
    CityEast,
    CityWest,
    CityEastOW,
    CityWestOW,
    Woodside_1F = 20,
    Woodside_2F,
    Woodside_3F,
    Hospital_FW_1F = 30,
    Hospital_FW_2F,
    Hospital_FW_3F,
    Hospital_FW_BF,
    Hospital_FW_RF,
    LakeviewHotel_OW_1F = 40,
    LakeviewHotel_OW_2F,
    LakeviewHotel_OW_3F,
    LakeviewHotel_OW_EF,
    LakeviewHotel_OW_BF,
    LakeviewHotel_OW_GF,
    LakeviewHotel_OW_VF,
    Hospital_OW_1F = 50,
    Hospital_OW_2F,
    Hospital_OW_3F,
    Hospital_OW_BF,
    Hospital_OW_RF,
    BlueCreek_1F = 60,
    BlueCreek_2F,
    BlueCreek_3F,
    BlueCreek_4F,
    Toluca_Prison_OW_BF = 70,
    Toluca_Prison_OW_2F = 72,
    Toluca_Prison_OW_3F,
    Toluca_Prison_OW_1F_Main,
    Toluca_Prison_OW_1F_Boar,
    Toluca_Prison_OW_1F_Serpent,
    LakeviewHotel_FW_BF = 80,
    LakeviewHotel_FW_EF,
    LakeviewHotel_FW_1F,
    LakeviewHotel_FW_2F,
    LakeviewHotel_FW_3F,
    Labyrinth_MainArea = 90,
    Labyrinth_DisgustPath,
    Labyrinth_FearPathUp,
    Labyrinth_FearPathDown,
    Labyrinth_AngerPath,
};

